### ISSUE TITLE
sass-lint quitting on syntax errors

### ISSUE THREAD

**Issue by mrchimp** [lambdacreatives/tofino#72]
sass-lint is a bit flaky. Any syntax error causes watch to exit.

**Comment by danimalweb** [comment]
I ran sass-lint (not the gulp task) directly against the scss files and I get the same error.

```
Daniels-MacBook-Pro:tofino daniel$ sass-lint assets/styles/**/*.scss
/usr/local/lib/node_modules/sass-lint/lib/groot.js:21
    throw new Error('Parsing error' + fileInfo + ': ' + e.message);
    ^

Error: Parsing error at assets/styles/base/nav.scss: Please check validity of the block starting from line #93
    at module.exports (/usr/local/lib/node_modules/sass-lint/lib/groot.js:21:11)
    at Function.sassLint.lintText (/usr/local/lib/node_modules/sass-lint/index.js:36:13)
    at /usr/local/lib/node_modules/sass-lint/index.js:91:21
    at Array.forEach (native)
    at Function.sassLint.lintFiles (/usr/local/lib/node_modules/sass-lint/index.js:90:9)
    at detectPattern (/usr/local/lib/node_modules/sass-lint/bin/sass-lint.js:15:18)
    at /usr/local/lib/node_modules/sass-lint/bin/sass-lint.js:81:5
    at Array.forEach (native)
    at Object.<anonymous> (/usr/local/lib/node_modules/sass-lint/bin/sass-lint.js:80:16)
    at Module._compile (module.js:434:26)```

This is related to a sass-lint dependency https://github.com/tonyganch/gonzales-pe (CSS Parser)
